### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by queball1999** [Receipt-Wrangler/receipt-wrangler-api#211]
I may try my hand at implementing some of these features but I also wanted to share them as suggestions for others to explore.

- Navigate back to the receipt list after clicking the save button. As of now, it stays on the form and I am required to click away. Even the back button here seems to get stuck and continuously loop me back to the receipt form.
- The multi-select combo boxes stay open after I select a single item which is rather frustrating. Also if I add a category or tag, I will see it created but the initial entry text remains which I then have to delete.
- Introduce more options for theming. Specifically, I'd like to change the background color, text color, images, etc.
- I don't know how to fix it, but the "All" category was a bit difficult to understand. Maybe introducing some instructions or adding tooltips would help.
- It would be nice to define the email and AI settings from the web page itself.
- Allowing multiple conditional statements (of the same type) per dashboard widget. I am not sure if I am missing something, but I would like to make a widget for each month of the year within the start and end date of the month.
- The ability to backup, export, and import the receipts. I know this can be done by backing up the database, etc, but for end users having an easy way to backup their data and import would be huge.
- The currency is in integers, when really it should be a floating-point integer. Sometimes I even get split by errors due to this.
- It seems like I don't have the AI settings setup quite right and I cannot quick scan an image in. This makes the mobile app almost useless as I cannot even upload a receipt and fill out the form after. 

So far I have really liked how simple and intuitive the software is and would very much like to contribute to this project. However, as of now my strongest programming language is Python so I will try my best. Feel free to leave feedback.

**Comment by Noah231515** [comment]
Hey thanks a bunch for the feedback.

1. Navigating to the list after saving makes a lot of sense. This for sure can be the pattern across the app. I will make an issue on the desktop to implement this.
2. In which cases is this most frustrating? Perhaps this could be configurable, since this is useful when adding multiple categories/tags on a receipt. Its tricky because its useful when you want to add more than one, but not as useful when you only want to add one.
3. Agreed. I'll do some initial research into this.
4. Take a look at https://receiptwrangler.io/docs/concepts/groups/overview#what-is-the-all-group, maybe this will help clear things up. Adding something in app could be useful here.
5. I will have to think about this a bit more. In the long run it probably is better to have these system settings configured via an interface. It is friendlier to do so and seems like a natural progression from config file driven settings to db driven settings. I did it this way initially to keep it simple, but it is time to start thinking more about ease of use.
6. Agreed, dashboards have yet to be really fleshed out yet.
8. Agreed, this is in the backlog.
9. What do you mean the currency is integers? (This may have been due to a bug with the input mask that was fixed today)
10. I can help you out with that. If you haven't done so already, read over the docs at https://receiptwrangler.io/docs/configuration/ on the AISettings section. What does your config look like atm?

**Comment by queball1999** [comment]
I will be reviewing everything and trying to make some small modifications before anything serious. I will definitely reach out if I have any questions.

Regarding your response:
1. Awesome!
2. Hmm, maybe if the mouse is detected in the drop-down menu it stays open, and if it goes outside, the menu will close? I think this may accommodate both use both cases because if I want one, I just have to select it and move my mouse out of the way.
3. Awesome!
4. Will do.
5. No worries, I understand your concerns. Feel free to stick with what you feel is best.
6. I suspected as much, nevertheless, it is always good to document features to be added.
7. Awesome!
8. For some odd reason, I can only define amounts as integers or whole numbers instead of floating-point integers. This causes the split totals of odd numbers to carry over the decimals, as in the image below. I entered the amount of $21 so it should be $10.5 for each and not $105. 
![image](https://github.com/Receipt-Wrangler/receipt-wrangler-api/assets/57122349/2a8cf275-5788-40e8-b86a-81ffb09e8f4f)
9. My AI config is as follows and it doesn't seem to work. I have blanked the openAI key but have verified it is valid. I want to start initially using openAI and then eventually switch to self-hosted.
![image](https://github.com/Receipt-Wrangler/receipt-wrangler-api/assets/57122349/4149542d-c073-497b-b617-ac46dc43a6dc)

**Comment by Noah231515** [comment]
2. Yeah I'll see what other apps do too. The way it is implemented now has always felt weird to me, but worked.
8. This issue was fixed in the latest PR in desktop. Get the latest version to have this fixed.
9. Do you post the contents of logs/app.log ?

**Comment by queball1999** [comment]
8. I was able to get this resolved by pulling the latest release. Thank you!
9. I still have not gotten this working and was unable to locate any logs. If I do docker logs <id> I do not see anything, and if I navigate to /etc/log I still do not see anything.

**Comment by queball1999** [comment]
Here is an image of my config; I am running the monolithic container. 
Initially the ./logs:/app/receipt-wrnagler-api/logs was missing and after I added it, I was able to access the logs.
Seems like my openAI key is wrong!
![image](https://github.com/Receipt-Wrangler/receipt-wrangler-api/assets/57122349/9087cd17-c09e-4564-bd69-76a2bea923b8)

**Comment by queball1999** [comment]
No worries, I appreciate your help.

You can continue to close this out but I did notice another item I thought I'd share:
- When I click on a receipt it seems like I instinctually want to be able to edit right away and have changes only takes effect when I click save. This would still allow me to cancel changes by backing out, navigating away, or not pressing save. I often forget that I didn't press the edit button and start trying to edit, only to be stopped in my tracks and have to then hit the button. I understand why this could be the default behavior, but maybe adding a setting for the instant edit would be nice. 

Again, I will hopefully start to contribute to this project. I am still getting the feel for everything and reviewing what you have already done. Thanks again for al the help!!

**Comment by Noah231515** [comment]
Love this idea, adding a backlog item for it.
