### ISSUE TITLE
"Unauthorized access to entity" when viewing receipt list

### ISSUE THREAD

**Issue by sypion** [Receipt-Wrangler/receipt-wrangler-api#95]
Navigating to the all group "Receipt List" AND attempting to save a receipt returns an error `Unauthorized access to entity.`

API container logs:
```
[2.900ms] [rows:0] SELECT * FROM "group_members" WHERE user_id = '3' AND group_id = 'all'
2023/08/11 21:01:50 /go/api/internal/repositories/group_members.go:53 ERROR: invalid input syntax for type bigint: "all" (SQLSTATE 22P02)
```

Currently using PostgreSQL as my database.

**Comment by Noah231515** [comment]
@sypion Did you try to set "All" as a group on a receipt by chance?
I know for a while this was possible, but should not be and has been fixed since. 

For context, this error only pops when a user in the group has an invalid role in the group for some action. Users cannot have a role in the "All" group since its basically a fake group that everyone has.

**Comment by sypion** [comment]
I see what you mean!

Creating a receipt under the `Home` group worked fine. Perhaps hide the `Receipt List` tab when under the `All` group to prevent further confusion?
